name: Compile doom to wasm
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build-doom:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{matrix.os}}
    steps:
      - uses: actions/checkout@v2
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: zig build -Dtarget=wasm32-wasi-musl -Doptimize=ReleaseFast
